"""empty message

Revision ID: 0a64e557ecde
Revises: a78e0cf07941
Create Date: 2023-11-11 10:24:44.824467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a64e557ecde'
down_revision = 'a78e0cf07941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('image1', sa.String(length=120), nullable=True),
    sa.Column('image2', sa.String(length=120), nullable=True),
    sa.Column('image3', sa.String(length=120), nullable=True),
    sa.Column('image4', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['users.id'], name=op.f('fk_issues_organization_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_issues_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=254), nullable=True),
    sa.Column('workhours', sa.String(length=254), nullable=True),
    sa.Column('attachment1', sa.String(length=254), nullable=True),
    sa.Column('attachment2', sa.String(length=254), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organizations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mbid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbid', sa.VARCHAR(), nullable=True))

    op.drop_table('organizations')
    op.drop_table('issues')
    # ### end Alembic commands ###
