"""empty message

Revision ID: 18d6a66ff2e9
Revises: 65459d7166db
Create Date: 2023-07-06 13:19:06.675636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d6a66ff2e9'
down_revision = '65459d7166db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
