"""empty message

Revision ID: 1e3fce724d6d
Revises: 5286af681b46
Create Date: 2023-03-07 12:39:25.156064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1e3fce724d6d'
down_revision = '5286af681b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('premium_amount', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer'))
    )
    op.drop_table('journals')
    op.drop_table('appointments')
    op.drop_table('webfeatures')
    op.drop_table('newsletter_contacts')
    op.drop_table('threads')
    op.drop_table('laundryrequests')
    op.drop_table('appearances')
    op.drop_table('destinations')
    op.drop_table('blocks')
    op.drop_table('payments')
    op.drop_table('bookings')
    op.drop_table('posts')
    op.drop_table('deliveries')
    op.drop_table('teams')
    op.drop_table('notes')
    op.drop_table('prices')
    op.drop_table('newsletter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recepients', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_newsletter')
    )
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('amount', sa.TEXT(), nullable=False),
    sa.Column('features', sa.TEXT(length=64), nullable=False),
    sa.Column('numsessions', sa.INTEGER(), nullable=True),
    sa.Column('numchatweeks', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_prices')
    )
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('therapist_id', sa.INTEGER(), nullable=True),
    sa.Column('appointment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_notes_appointment_id_appointments'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name='fk_notes_therapist_id_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notes_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_notes')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('faceboook', sa.VARCHAR(length=140), nullable=True),
    sa.Column('instagram', sa.INTEGER(), nullable=True),
    sa.Column('twitter', sa.INTEGER(), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('destination_id', sa.INTEGER(), nullable=True),
    sa.Column('traveler_id', sa.INTEGER(), nullable=True),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=120), nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('item_description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('item_weight', sa.FLOAT(), nullable=True),
    sa.Column('item_dimension', sa.VARCHAR(length=120), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('sender_location_id', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('arrival_date', sa.DATE(), nullable=True),
    sa.Column('ticket', sa.VARCHAR(length=255), nullable=True),
    sa.Column('traveller_note', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='fk_deliveries_agent_id_users'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name='fk_deliveries_destination_id_destinations'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_deliveries_sender_id_users'),
    sa.ForeignKeyConstraint(['sender_location_id'], ['destinations.id'], name='fk_deliveries_sender_location_id_destinations'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], name='fk_deliveries_traveler_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_deliveries')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('thread_id', sa.INTEGER(), nullable=False),
    sa.Column('main', sa.VARCHAR(length=5), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='fk_posts_thread_id_threads'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_posts_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_posts')
    )
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('therapist_id', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['webfeatures.id'], name='fk_bookings_therapist_id_webfeatures'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bookings_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_bookings')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('tx_ref', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['prices.id'], name='fk_payments_plan_id_prices'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_payments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_payments')
    )
    op.create_table('blocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('block_type', sa.VARCHAR(), nullable=True),
    sa.Column('appearance_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['appearance_id'], ['appearances.id'], name='fk_blocks_appearance_id_appearances'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('country', sa.VARCHAR(length=80), nullable=True),
    sa.Column('city', sa.VARCHAR(length=80), nullable=True),
    sa.Column('agent_ids', sqlite.JSON(), nullable=True),
    sa.Column('airport_name', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_destinations')
    )
    op.create_table('appearances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('subtitle_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('paragraph_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_font', sa.VARCHAR(length=64), nullable=True),
    sa.Column('subtitle_font', sa.VARCHAR(length=64), nullable=True),
    sa.Column('paragraph_font', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_size', sa.INTEGER(), nullable=True),
    sa.Column('subtitle_size', sa.INTEGER(), nullable=True),
    sa.Column('paragraph_size', sa.INTEGER(), nullable=True),
    sa.Column('bootstrap_class1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('bootstrap_class2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('bootstrap_class3', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laundryrequests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pickup_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('hostel', sa.VARCHAR(length=80), nullable=True),
    sa.Column('floor', sa.VARCHAR(length=80), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=80), nullable=True),
    sa.Column('location', sa.VARCHAR(length=80), nullable=True),
    sa.Column('price', sa.VARCHAR(length=80), nullable=True),
    sa.Column('uid', sa.VARCHAR(length=80), nullable=True),
    sa.Column('note', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_laundryrequests_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_laundryrequests')
    )
    op.create_table('threads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_threads_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_threads')
    )
    op.create_table('newsletter_contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_newsletter_contacts')
    )
    op.create_table('webfeatures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('wtext', sa.TEXT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_webfeatures')
    )
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('therapist_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), nullable=True),
    sa.Column('therapist_confirmation', sa.VARCHAR(length=10), nullable=True),
    sa.Column('user_confirmation', sa.VARCHAR(length=10), nullable=True),
    sa.Column('user_notes', sa.VARCHAR(length=250), nullable=True),
    sa.Column('therapist_notes', sa.VARCHAR(length=250), nullable=True),
    sa.Column('meeting_link', sa.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name='fk_appointments_therapist_id_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_appointments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_appointments')
    )
    op.create_table('journals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_journals_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_journals')
    )
    op.drop_table('farmer')
    # ### end Alembic commands ###
