"""empty message

Revision ID: 233dd0c61d85
Revises: c68f50296060
Create Date: 2022-07-03 06:17:02.764420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233dd0c61d85'
down_revision = 'c68f50296060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rookings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rookings')
    # ### end Alembic commands ###
