"""empty message

Revision ID: 281edb263104
Revises: 233dd0c61d85
Create Date: 2022-07-05 13:50:30.878287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281edb263104'
down_revision = '233dd0c61d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_therapist_id_webfeatures', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookings_therapist_id_users'), 'users', ['therapist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_therapist_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bookings_therapist_id_webfeatures', 'webfeatures', ['therapist_id'], ['id'])

    # ### end Alembic commands ###
