"""empty message

Revision ID: 2af5df1ad4e2
Revises: 5daa53fd8965
Create Date: 2022-07-19 09:05:06.312130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af5df1ad4e2'
down_revision = '5daa53fd8965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_medium', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pref_therapistgender', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pref_help', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pref_help')
        batch_op.drop_column('pref_therapistgender')
        batch_op.drop_column('pref_medium')

    # ### end Alembic commands ###
