"""teams table

Revision ID: 30e25721fb50
Revises: c44ce36d4057
Create Date: 2021-12-06 04:18:54.735780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e25721fb50'
down_revision = 'c44ce36d4057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('faceboook', sa.String(length=140), nullable=True),
    sa.Column('instagram', sa.Integer(), nullable=True),
    sa.Column('twitter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('faceboook', sa.VARCHAR(length=140), nullable=True),
    sa.Column('instagram', sa.INTEGER(), nullable=True),
    sa.Column('twitter', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teams')
    # ### end Alembic commands ###
