"""abooutsub

Revision ID: 380286f5581d
Revises: 927e4c7de14b
Create Date: 2021-12-04 16:41:28.643195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380286f5581d'
down_revision = '927e4c7de14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_feature', 'paragraph')
    op.drop_column('web_feature', 'subtitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_feature', sa.Column('subtitle', sa.VARCHAR(length=140), nullable=True))
    op.add_column('web_feature', sa.Column('paragraph', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
