"""empty message

Revision ID: 3804b0e9fd0e
Revises: c1c6c9e71b53
Create Date: 2023-01-20 19:41:26.833486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3804b0e9fd0e'
down_revision = 'c1c6c9e71b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_location_id_destinations'), 'destinations', ['location_id'], ['id'])
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_users_location_id_destinations'), type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
