"""empty message

Revision ID: 389579c0c9cc
Revises: b6fa7a21ec68
Create Date: 2022-12-27 17:50:10.230563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389579c0c9cc'
down_revision = 'b6fa7a21ec68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
