"""empty message

Revision ID: 395df0feedd5
Revises: b146a98b6d55
Create Date: 2022-12-17 08:40:16.430505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395df0feedd5'
down_revision = 'b146a98b6d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepients', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter'))
    )
    op.create_table('newsletter_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_contacts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_contacts')
    op.drop_table('newsletter')
    # ### end Alembic commands ###
