"""empty message

Revision ID: 3e452b15a75f
Revises: 9b9cf39d4e60
Create Date: 2023-11-14 19:58:56.232601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e452b15a75f'
down_revision = '9b9cf39d4e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('issue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('issue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
