"""empty message

Revision ID: 4768637815ae
Revises: 30e25721fb50
Create Date: 2021-12-06 23:34:27.008043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4768637815ae'
down_revision = '30e25721fb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('picture', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'picture')
    # ### end Alembic commands ###
