"""empty message

Revision ID: 4fa4a0491da5
Revises: dc8698ad923f
Create Date: 2023-02-18 19:33:14.370570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa4a0491da5'
down_revision = 'dc8698ad923f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partrequests', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
