"""abutimage and subtitle

Revision ID: 505a32399943
Revises: 4768637815ae
Create Date: 2021-12-07 20:28:25.138144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505a32399943'
down_revision = '4768637815ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('about_image', sa.String(length=64), nullable=False))
    op.add_column('about', sa.Column('logo', sa.String(length=64), nullable=True))
    op.add_column('about', sa.Column('carousel_image_1', sa.String(length=64), nullable=True))
    op.drop_column('about', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('image', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('about', 'carousel_image_1')
    op.drop_column('about', 'logo')
    op.drop_column('about', 'about_image')
    # ### end Alembic commands ###
