"""empty message

Revision ID: 5385149b2f22
Revises: e1741ce758bf
Create Date: 2022-12-13 21:37:58.563287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5385149b2f22'
down_revision = 'e1741ce758bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseprice', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('baseprice')

    # ### end Alembic commands ###
