"""empty message

Revision ID: 5d8f3aa53f68
Revises: db8b09e2a3ff
Create Date: 2023-11-11 17:59:10.704911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8f3aa53f68'
down_revision = 'db8b09e2a3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('views', sa.String(length=255), nullable=True),
    sa.Column('likes', sa.String(length=255), nullable=True),
    sa.Column('dislikes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussions'))
    )
    op.create_table('discussioncomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], name=op.f('fk_discussioncomments_discussion_id_discussions')),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['discussioncomments.id'], name=op.f('fk_discussioncomments_parent_comment_id_discussioncomments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discussioncomments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussioncomments'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('disklikes', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('views', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('disklikes')
        batch_op.drop_column('likes')

    op.drop_table('discussioncomments')
    op.drop_table('discussions')
    # ### end Alembic commands ###
