"""empty message

Revision ID: 65459d7166db
Revises: ca04fe7e026b
Create Date: 2023-07-05 18:44:13.872423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65459d7166db'
down_revision = 'ca04fe7e026b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_student_results_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_student_results_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
