"""empty message

Revision ID: 65ef08eeec12
Revises: 622a21efa32f
Create Date: 2023-03-06 00:44:40.546618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ef08eeec12'
down_revision = '622a21efa32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_review_vendor_id_users'), 'users', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_vendor_id_users'), type_='foreignkey')
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
