"""empty message

Revision ID: 662fe4e42b8d
Revises: d94bf48f9be2
Create Date: 2023-11-12 20:50:02.389958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662fe4e42b8d'
down_revision = 'd94bf48f9be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('issue_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discussion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_likes_issue_id_issues'), 'issues', ['issue_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_likes_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_likes_discussion_id_discussions'), 'discussions', ['discussion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_likes_poll_id_polls'), 'polls', ['poll_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_poll_id_polls'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_likes_discussion_id_discussions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_likes_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_likes_issue_id_issues'), type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('discussion_id')
        batch_op.drop_column('issue_id')
        batch_op.drop_column('poll_id')

    # ### end Alembic commands ###
