"""empty message

Revision ID: 67eea936baec
Revises: ad40540e3bcb
Create Date: 2023-01-20 06:18:06.949943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67eea936baec'
down_revision = 'ad40540e3bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('agent_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('airport_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinations'))
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('delivery_status', sa.String(length=120), nullable=True),
    sa.Column('item_name', sa.String(length=120), nullable=True),
    sa.Column('item_description', sa.String(length=120), nullable=True),
    sa.Column('item_weight', sa.Float(), nullable=True),
    sa.Column('item_dimension', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_deliveries_agent_id_users')),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_deliveries_destination_id_destinations')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_deliveries_sender_id_users')),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], name=op.f('fk_deliveries_traveler_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('destinations')
    # ### end Alembic commands ###
