"""empty message

Revision ID: 687c54d50291
Revises: cb3221527a66
Create Date: 2023-11-11 18:54:30.904000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687c54d50291'
down_revision = 'cb3221527a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discussions_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discussions_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
