"""empty message

Revision ID: 6c4458f0ea4e
Revises: 1d5e39bc0c5f
Create Date: 2023-03-05 11:18:03.555383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4458f0ea4e'
down_revision = '1d5e39bc0c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returnable', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('return_period', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('return_period')
        batch_op.drop_column('returnable')

    # ### end Alembic commands ###
