"""empty message

Revision ID: 6eee0e4a14ab
Revises: f478c3ab098c
Create Date: 2023-08-29 17:15:29.829908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eee0e4a14ab'
down_revision = 'f478c3ab098c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airtimetopups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payername', sa.String(length=106), nullable=True),
    sa.Column('payermobile', sa.String(length=106), nullable=True),
    sa.Column('payeremail', sa.String(length=106), nullable=True),
    sa.Column('recipientmobile', sa.String(length=106), nullable=True),
    sa.Column('amount', sa.String(length=106), nullable=True),
    sa.Column('merchtxnref', sa.String(length=106), nullable=True),
    sa.Column('countryid', sa.String(length=106), nullable=True),
    sa.Column('oprid', sa.String(length=106), nullable=True),
    sa.Column('vouchernumber', sa.String(length=106), nullable=True),
    sa.Column('type', sa.String(length=106), nullable=True),
    sa.Column('payerbankacctno', sa.String(length=106), nullable=True),
    sa.Column('payerbankaccttitle', sa.String(length=106), nullable=True),
    sa.Column('bankbranchsortcode', sa.String(length=106), nullable=True),
    sa.Column('payermsisdn', sa.String(length=106), nullable=True),
    sa.Column('recepientmsisdn', sa.String(length=106), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airtimetopups'))
    )
    op.create_table('cdrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('call_direction', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('contact_id', sa.String(length=50), nullable=True),
    sa.Column('queue_extension', sa.String(length=20), nullable=True),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('agent_first_name', sa.String(length=50), nullable=True),
    sa.Column('agent_last_name', sa.String(length=50), nullable=True),
    sa.Column('agent_email', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('duration_timespan', sa.String(length=50), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('call_start_time_local', sa.DateTime(), nullable=True),
    sa.Column('call_start_time_utc', sa.DateTime(), nullable=True),
    sa.Column('call_established_time_local', sa.DateTime(), nullable=True),
    sa.Column('call_established_time_utc', sa.DateTime(), nullable=True),
    sa.Column('call_end_time_local', sa.DateTime(), nullable=True),
    sa.Column('call_end_time_utc', sa.DateTime(), nullable=True),
    sa.Column('call_start_time_local_millis', sa.BigInteger(), nullable=True),
    sa.Column('call_start_time_utc_millis', sa.BigInteger(), nullable=True),
    sa.Column('call_established_time_local_millis', sa.BigInteger(), nullable=True),
    sa.Column('call_established_time_utc_millis', sa.BigInteger(), nullable=True),
    sa.Column('call_end_time_local_millis', sa.BigInteger(), nullable=True),
    sa.Column('call_end_time_utc_millis', sa.BigInteger(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('inbound_call_text', sa.Text(), nullable=True),
    sa.Column('missed_call_text', sa.Text(), nullable=True),
    sa.Column('outbound_call_text', sa.Text(), nullable=True),
    sa.Column('not_answered_outbound_call_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cdrs'))
    )
    op.create_table('extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=106), nullable=True),
    sa.Column('password', sa.String(length=106), nullable=True),
    sa.Column('ip', sa.String(length=106), nullable=True),
    sa.Column('channels', sa.String(length=106), nullable=True),
    sa.Column('company_id', sa.String(length=106), nullable=True),
    sa.Column('siprequest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['siprequest_id'], ['siprequests.id'], name=op.f('fk_extensions_siprequest_id_siprequests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extensions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extensions')
    op.drop_table('cdrs')
    op.drop_table('airtimetopups')
    # ### end Alembic commands ###
