"""empty message

Revision ID: 72285eee5b03
Revises: d1be716967b8
Create Date: 2022-07-02 13:21:49.956304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72285eee5b03'
down_revision = 'd1be716967b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numsessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numchatweeks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_column('numchatweeks')
        batch_op.drop_column('numsessions')

    # ### end Alembic commands ###
