"""empty message

Revision ID: 7ab690451ba2
Revises: 19340abd0234
Create Date: 2023-03-08 00:36:39.650298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab690451ba2'
down_revision = '19340abd0234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecom_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('cashcode', sa.String(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_ecom_request_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ecom_request'))
    )
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('cashcode', sa.VARCHAR(), nullable=True),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name='fk_request_farmer_id_farmers'),
    sa.PrimaryKeyConstraint('id', name='pk_request')
    )
    op.drop_table('ecom_request')
    # ### end Alembic commands ###
