"""empty message

Revision ID: 7e35860be6ba
Revises: 0b4083b5d0d0
Create Date: 2023-07-07 00:39:59.796399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e35860be6ba'
down_revision = '0b4083b5d0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_year', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('completed_year')

    # ### end Alembic commands ###
