"""empty message

Revision ID: 7e6722a5bdd9
Revises: 2af5df1ad4e2
Create Date: 2022-07-24 22:03:54.329136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6722a5bdd9'
down_revision = '2af5df1ad4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['prices.id'], name=op.f('fk_payments_plan_id_prices')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmed', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('rec_payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_rec_payment_id_payments'), 'payments', ['rec_payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_rec_payment_id_payments'), type_='foreignkey')
        batch_op.drop_column('rec_payment_id')
        batch_op.drop_column('payment_confirmed')

    op.drop_table('payments')
    # ### end Alembic commands ###
