"""empty message

Revision ID: 80cedae3bf6f
Revises: f8174e03f51f
Create Date: 2023-05-23 13:25:10.132389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cedae3bf6f'
down_revision = 'f8174e03f51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecom_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposition', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sms_disposition', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecom_request', schema=None) as batch_op:
        batch_op.drop_column('sms_disposition')
        batch_op.drop_column('disposition')

    # ### end Alembic commands ###
