"""empty message

Revision ID: 81968d7146c8
Revises: 5b6dd3455b7f
Create Date: 2022-07-06 13:11:32.981943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81968d7146c8'
down_revision = '5b6dd3455b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
