"""empty message

Revision ID: 850de668e557
Revises: 368d16413782
Create Date: 2022-07-24 22:12:32.848351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850de668e557'
down_revision = '368d16413782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_ref', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('tx_ref')

    # ### end Alembic commands ###
