"""more roows in aboout

Revision ID: 87047e6473f5
Revises: 1d88c789bbd0
Create Date: 2021-12-05 01:31:11.849868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87047e6473f5'
down_revision = '1d88c789bbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('faq_title', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('faq_subtitle', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('faq_paragraph', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('testimonial_title', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('testimonial_subtitle', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('testimonial_paragraph', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('team_title', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('team_subtitle', sa.String(length=140), nullable=True))
    op.add_column('about', sa.Column('team_paragraph', sa.String(length=140), nullable=True))
    op.drop_column('about', 'feature_paragraph')
    op.drop_column('about', 'feature_subtitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('feature_subtitle', sa.VARCHAR(length=140), nullable=True))
    op.add_column('about', sa.Column('feature_paragraph', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('about', 'team_paragraph')
    op.drop_column('about', 'team_subtitle')
    op.drop_column('about', 'team_title')
    op.drop_column('about', 'testimonial_paragraph')
    op.drop_column('about', 'testimonial_subtitle')
    op.drop_column('about', 'testimonial_title')
    op.drop_column('about', 'faq_paragraph')
    op.drop_column('about', 'faq_subtitle')
    op.drop_column('about', 'faq_title')
    # ### end Alembic commands ###
