"""empty message

Revision ID: 8d26bd53edf3
Revises: 6c4458f0ea4e
Create Date: 2023-03-05 13:08:23.473723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d26bd53edf3'
down_revision = '6c4458f0ea4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery', sa.String(length=16), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('delivery')

    # ### end Alembic commands ###
