"""empty message

Revision ID: 8dbe0e7c3ca6
Revises: d5c0d8a55044
Create Date: 2023-08-19 22:06:49.059978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbe0e7c3ca6'
down_revision = 'd5c0d8a55044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siprequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=106), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siprequests', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
