"""webfeatures

Revision ID: 927e4c7de14b
Revises: 0eed04de8f93
Create Date: 2021-12-04 16:29:14.197759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927e4c7de14b'
down_revision = '0eed04de8f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_feature', sa.Column('subtitle', sa.String(length=140), nullable=False))
    op.add_column('web_feature', sa.Column('paragraph', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_feature', 'paragraph')
    op.drop_column('web_feature', 'subtitle')
    # ### end Alembic commands ###
