"""empty message

Revision ID: 9b9cf39d4e60
Revises: a0b25f20fdd0
Create Date: 2023-11-14 19:22:01.133015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9cf39d4e60'
down_revision = 'a0b25f20fdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_upload_issue_id_issues')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_upload_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload'))
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))

    op.drop_table('upload')
    # ### end Alembic commands ###
