"""empty message

Revision ID: 9deddf24bc0a
Revises: 1b073674d5ab
Create Date: 2022-06-30 22:15:27.950423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9deddf24bc0a'
down_revision = '1b073674d5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
