"""empty message

Revision ID: a3d61ba90d1c
Revises: 4fa4a0491da5
Create Date: 2023-02-19 08:13:02.594415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d61ba90d1c'
down_revision = '4fa4a0491da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partrequests', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
