"""empty message

Revision ID: a78e0cf07941
Revises: 458b48ba2ded
Create Date: 2023-11-07 08:46:27.615346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78e0cf07941'
down_revision = '458b48ba2ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdrs')
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_index('ix_about_email')

    op.drop_table('about')
    op.drop_table('contacts')
    op.drop_table('siprequests')
    op.drop_table('airtimetopups')
    op.drop_table('extensions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbid', sa.String(), nullable=True))
        batch_op.drop_column('company_id')
        batch_op.drop_column('blocksused')
        batch_op.drop_column('endblock')
        batch_op.drop_column('blockid')
        batch_op.drop_column('startblock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startblock', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('blockid', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('endblock', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('blocksused', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('mbid')

    op.create_table('extensions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=106), nullable=True),
    sa.Column('password', sa.VARCHAR(length=106), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=106), nullable=True),
    sa.Column('channels', sa.VARCHAR(length=106), nullable=True),
    sa.Column('company_id', sa.VARCHAR(length=106), nullable=True),
    sa.Column('siprequest_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['siprequest_id'], ['siprequests.id'], name='fk_extensions_siprequest_id_siprequests'),
    sa.PrimaryKeyConstraint('id', name='pk_extensions')
    )
    op.create_table('airtimetopups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payername', sa.VARCHAR(length=106), nullable=True),
    sa.Column('payermobile', sa.VARCHAR(length=106), nullable=True),
    sa.Column('payeremail', sa.VARCHAR(length=106), nullable=True),
    sa.Column('recipientmobile', sa.VARCHAR(length=106), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=106), nullable=True),
    sa.Column('merchtxnref', sa.VARCHAR(length=106), nullable=True),
    sa.Column('countryid', sa.VARCHAR(length=106), nullable=True),
    sa.Column('oprid', sa.VARCHAR(length=106), nullable=True),
    sa.Column('vouchernumber', sa.VARCHAR(length=106), nullable=True),
    sa.Column('type', sa.VARCHAR(length=106), nullable=True),
    sa.Column('payerbankacctno', sa.VARCHAR(length=106), nullable=True),
    sa.Column('payerbankaccttitle', sa.VARCHAR(length=106), nullable=True),
    sa.Column('bankbranchsortcode', sa.VARCHAR(length=106), nullable=True),
    sa.Column('payermsisdn', sa.VARCHAR(length=106), nullable=True),
    sa.Column('recepientmsisdn', sa.VARCHAR(length=106), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_airtimetopups')
    )
    op.create_table('siprequests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('channels', sa.VARCHAR(length=128), nullable=True),
    sa.Column('other', sa.VARCHAR(length=512), nullable=True),
    sa.Column('codecs', sa.INTEGER(), nullable=True),
    sa.Column('inbound', sa.VARCHAR(length=128), nullable=True),
    sa.Column('outbound', sa.VARCHAR(length=128), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=128), nullable=True),
    sa.Column('certificate', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('email', sa.VARCHAR(length=106), nullable=True),
    sa.Column('name', sa.VARCHAR(length=106), nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=106), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=106), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_siprequests_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_siprequests')
    )
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_mobile', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_mobile2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_home', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_home2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_business', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_business2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_other', sa.VARCHAR(length=20), nullable=True),
    sa.Column('contact_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_contacts')
    )
    op.create_table('about',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('image', sa.VARCHAR(length=64), nullable=True),
    sa.Column('about_image', sa.VARCHAR(length=64), nullable=True),
    sa.Column('location', sa.VARCHAR(length=140), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('contact_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('about_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('feature_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('feature_paragraph', sa.TEXT(), nullable=True),
    sa.Column('faq_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('faq_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('faq_paragraph', sa.VARCHAR(length=140), nullable=True),
    sa.Column('testimonial_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('testimonial_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('testimonial_paragraph', sa.VARCHAR(length=140), nullable=True),
    sa.Column('team_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('team_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('team_paragraph', sa.VARCHAR(length=140), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=64), nullable=True),
    sa.Column('carousel_image_1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('atext', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_about')
    )
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.create_index('ix_about_email', ['email'], unique=False)

    op.create_table('cdrs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('call_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('call_direction', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('queue_extension', sa.VARCHAR(length=20), nullable=True),
    sa.Column('agent', sa.VARCHAR(length=50), nullable=True),
    sa.Column('agent_first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('agent_last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('agent_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('duration_timespan', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date_time', sa.DATETIME(), nullable=True),
    sa.Column('call_start_time_local', sa.DATETIME(), nullable=True),
    sa.Column('call_start_time_utc', sa.DATETIME(), nullable=True),
    sa.Column('call_established_time_local', sa.DATETIME(), nullable=True),
    sa.Column('call_established_time_utc', sa.DATETIME(), nullable=True),
    sa.Column('call_end_time_local', sa.DATETIME(), nullable=True),
    sa.Column('call_end_time_utc', sa.DATETIME(), nullable=True),
    sa.Column('call_start_time_local_millis', sa.BIGINT(), nullable=True),
    sa.Column('call_start_time_utc_millis', sa.BIGINT(), nullable=True),
    sa.Column('call_established_time_local_millis', sa.BIGINT(), nullable=True),
    sa.Column('call_established_time_utc_millis', sa.BIGINT(), nullable=True),
    sa.Column('call_end_time_local_millis', sa.BIGINT(), nullable=True),
    sa.Column('call_end_time_utc_millis', sa.BIGINT(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=True),
    sa.Column('inbound_call_text', sa.TEXT(), nullable=True),
    sa.Column('missed_call_text', sa.TEXT(), nullable=True),
    sa.Column('outbound_call_text', sa.TEXT(), nullable=True),
    sa.Column('not_answered_outbound_call_text', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_cdrs')
    )
    # ### end Alembic commands ###
