"""empty message

Revision ID: aa78429a033f
Revises: 4aa259730240
Create Date: 2023-02-19 19:51:52.598375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa78429a033f'
down_revision = '4aa259730240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_users_location_id_destinations', type_='foreignkey')
        batch_op.drop_constraint('fk_users_plan_id_prices', type_='foreignkey')
        batch_op.drop_constraint('fk_users_therapist_id_webfeatures', type_='foreignkey')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('rem_sessions')
        batch_op.drop_column('pref_help')
        batch_op.drop_column('therapist_id')
        batch_op.drop_column('payment_confirmed')
        batch_op.drop_column('baseprice')
        batch_op.drop_column('pref_therapistgender')
        batch_op.drop_column('pref_medium')
        batch_op.drop_column('plan_id')
        batch_op.drop_column('qualifications')
        batch_op.drop_column('platforms')
        batch_op.drop_column('license_number')
        batch_op.drop_column('rec_transaction_id')
        batch_op.drop_column('rem_chatweeks')
        batch_op.drop_column('location_id')
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rem_chatweeks', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rec_transaction_id', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('platforms', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('qualifications', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('plan_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pref_medium', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('pref_therapistgender', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('baseprice', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('therapist_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pref_help', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rem_sessions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_users_therapist_id_webfeatures', 'webfeatures', ['therapist_id'], ['id'])
        batch_op.create_foreign_key('fk_users_plan_id_prices', 'prices', ['plan_id'], ['id'])
        batch_op.create_foreign_key('fk_users_location_id_destinations', 'destinations', ['location_id'], ['id'])
        batch_op.drop_column('business_name')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
