"""abutimage and subtitle

Revision ID: b59f6d8caf6a
Revises: 505a32399943
Create Date: 2021-12-07 20:29:50.486472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59f6d8caf6a'
down_revision = '505a32399943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('about_image', sa.String(length=64), nullable=True))
    op.add_column('about', sa.Column('logo', sa.String(length=64), nullable=True))
    op.add_column('about', sa.Column('carousel_image_1', sa.String(length=64), nullable=True))
    op.drop_column('about', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('image', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('about', 'carousel_image_1')
    op.drop_column('about', 'logo')
    op.drop_column('about', 'about_image')
    # ### end Alembic commands ###
