"""empty message

Revision ID: bef617513850
Revises: a3d61ba90d1c
Create Date: 2023-02-19 08:14:48.364168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef617513850'
down_revision = 'a3d61ba90d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=128), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partrequests', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('note')

    # ### end Alembic commands ###
