"""abutimage and subtitle

Revision ID: c01f408e6da1
Revises: b59f6d8caf6a
Create Date: 2021-12-07 20:32:40.734279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01f408e6da1'
down_revision = 'b59f6d8caf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('image', sa.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
