"""empty message

Revision ID: c1c6c9e71b53
Revises: d6e1269e4453
Create Date: 2023-01-20 08:09:18.286287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c6c9e71b53'
down_revision = 'd6e1269e4453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_deliveries_sender_location_id_destinations'), 'destinations', ['sender_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deliveries_sender_location_id_destinations'), type_='foreignkey')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('note')
        batch_op.drop_column('sender_location_id')

    # ### end Alembic commands ###
