"""teams table

Revision ID: c44ce36d4057
Revises: 6fc8fc940273
Create Date: 2021-12-05 13:51:47.909548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44ce36d4057'
down_revision = '6fc8fc940273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('faceboook', sa.String(length=140), nullable=True),
    sa.Column('instagram', sa.Integer(), nullable=True),
    sa.Column('twitter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
