"""empty message

Revision ID: ca04fe7e026b
Revises: ff92117feab4
Create Date: 2023-07-05 18:42:39.078647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca04fe7e026b'
down_revision = 'ff92117feab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_student_results_student_id_users'), 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_results_student_id_users'), type_='foreignkey')
        batch_op.drop_column('student_id')

    op.drop_table('subjects')
    # ### end Alembic commands ###
