"""empty message

Revision ID: caf5a17541f0
Revises: 6733500c44e1
Create Date: 2023-11-12 20:25:00.241437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf5a17541f0'
down_revision = '6733500c44e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('likeable_id', sa.Integer(), nullable=False),
    sa.Column('likeable_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_likes'))
    )
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.VARCHAR(length=254), nullable=True))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('likes')
    # ### end Alembic commands ###
