"""empty message

Revision ID: d08716439f61
Revises: 7afe89c7c875
Create Date: 2022-07-24 23:14:03.258838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08716439f61'
down_revision = '7afe89c7c875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rec_transaction_id', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rec_transaction_id')

    # ### end Alembic commands ###
