"""empty message

Revision ID: d1be716967b8
Revises: b0f143d2e497
Create Date: 2022-07-02 12:27:41.454119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1be716967b8'
down_revision = 'b0f143d2e497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('amount', sa.Text(), nullable=False),
    sa.Column('features', sa.Text(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices'))
    )
    op.drop_table('price')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rem_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rem_chatweeks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_plan_id_prices'), 'prices', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_plan_id_prices'), type_='foreignkey')
        batch_op.drop_column('plan_id')
        batch_op.drop_column('rem_chatweeks')
        batch_op.drop_column('rem_sessions')

    op.create_table('price',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('amount', sa.TEXT(), nullable=False),
    sa.Column('features', sa.TEXT(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prices')
    # ### end Alembic commands ###
