"""empty message

Revision ID: d5c0d8a55044
Revises: 7e35860be6ba
Create Date: 2023-08-15 17:25:41.441959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c0d8a55044'
down_revision = '7e35860be6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siprequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channels', sa.String(length=128), nullable=True),
    sa.Column('other', sa.String(length=512), nullable=True),
    sa.Column('codecs', sa.Integer(), nullable=True),
    sa.Column('inbound', sa.String(length=128), nullable=True),
    sa.Column('outbound', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('certificate', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_siprequests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_siprequests'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siprequests')
    # ### end Alembic commands ###
