"""empty message

Revision ID: d94bf48f9be2
Revises: caf5a17541f0
Create Date: 2023-11-12 20:36:02.863478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94bf48f9be2'
down_revision = 'caf5a17541f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
