"""empty message

Revision ID: dc8698ad923f
Revises: 85dc131c0536
Create Date: 2023-02-18 14:47:23.899516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8698ad923f'
down_revision = '85dc131c0536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laundryrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hostel', sa.String(length=80), nullable=True),
    sa.Column('floor', sa.String(length=80), nullable=True),
    sa.Column('room_number', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('uid', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_laundryrequests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laundryrequests'))
    )
    op.create_table('partrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('car_make', sa.String(length=128), nullable=False),
    sa.Column('car_model', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_partrequests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partrequests'))
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['partrequests.id'], name=op.f('fk_bids_part_id_partrequests')),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], name=op.f('fk_bids_vendor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('partrequests')
    op.drop_table('laundryrequests')
    # ### end Alembic commands ###
