"""empty message

Revision ID: e1bebbe823e1
Revises: 5385149b2f22
Create Date: 2022-12-14 19:14:52.487409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bebbe823e1'
down_revision = '5385149b2f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('therapist_confirmation', sa.String(length=10), nullable=True),
    sa.Column('user_confirmation', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_appointments_therapist_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_appointments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
