"""abutimage and subtitle

Revision ID: e350b486b431
Revises: bf2f74e043bd
Create Date: 2021-12-07 20:36:34.920163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e350b486b431'
down_revision = 'bf2f74e043bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('image', sa.String(length=64), nullable=True))
    op.drop_column('about', 'about_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('about_image', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('about', 'image')
    # ### end Alembic commands ###
