"""empty message

Revision ID: e9aa581266e2
Revises: 09ec85f51d38
Create Date: 2022-06-30 10:41:39.150841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9aa581266e2'
down_revision = '09ec85f51d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_feature', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
