"""empty message

Revision ID: f478c3ab098c
Revises: 4b7e871d66c4
Create Date: 2023-08-23 09:17:43.672869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f478c3ab098c'
down_revision = '4b7e871d66c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('farmers')
    op.drop_table('subjects')
    op.drop_table('student_results')
    op.drop_table('ecom_request')
    op.drop_table('partrequests')
    op.drop_table('review')
    with op.batch_alter_table('siprequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=106), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siprequests', schema=None) as batch_op:
        batch_op.drop_column('ip')

    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_review_user_id_users'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], name='fk_review_vendor_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_review')
    )
    op.create_table('partrequests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=False),
    sa.Column('model_year', sa.INTEGER(), nullable=False),
    sa.Column('car_make', sa.VARCHAR(length=128), nullable=False),
    sa.Column('car_model', sa.VARCHAR(length=128), nullable=False),
    sa.Column('note', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_partrequests_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_partrequests')
    )
    op.create_table('ecom_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('cashcode', sa.VARCHAR(), nullable=True),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('disposition', sa.VARCHAR(), nullable=True),
    sa.Column('sms_disposition', sa.VARCHAR(), nullable=True),
    sa.Column('sms_attempts', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name='fk_ecom_request_farmer_id_farmers'),
    sa.PrimaryKeyConstraint('id', name='pk_ecom_request')
    )
    op.create_table('student_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('year', sa.VARCHAR(length=128), nullable=True),
    sa.Column('result', sa.INTEGER(), nullable=False),
    sa.Column('index_number', sa.VARCHAR(length=128), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_student_results_student_id_users'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='fk_student_results_subject_id_subjects'),
    sa.PrimaryKeyConstraint('id', name='pk_student_results')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_subjects')
    )
    op.create_table('farmers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('premium_amount', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cashcode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_added', sa.DATE(), nullable=True),
    sa.Column('last_modified', sa.DATE(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=255), nullable=True),
    sa.Column('society', sa.VARCHAR(length=255), nullable=True),
    sa.Column('farmercode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cooperative', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ordernumber', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_farmers')
    )
    op.create_table('bids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('delivery', sa.VARCHAR(length=16), nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['partrequests.id'], name='fk_bids_part_id_partrequests'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], name='fk_bids_vendor_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_bids')
    )
    # ### end Alembic commands ###
