"""empty message

Revision ID: f8174e03f51f
Revises: 7ab690451ba2
Create Date: 2023-05-02 22:52:45.008206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8174e03f51f'
down_revision = '7ab690451ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordernumber', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('ordernumber')

    # ### end Alembic commands ###
