"""empty message

Revision ID: fe89f0d53f16
Revises: 0a64e557ecde
Create Date: 2023-11-11 11:48:17.539702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe89f0d53f16'
down_revision = '0a64e557ecde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_constraint('fk_issues_organization_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_issues_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_issues_organization_id_organizations'), type_='foreignkey')
        batch_op.create_foreign_key('fk_issues_organization_id_users', 'users', ['organization_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
